// dart format off
// coverage:ignore-file
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unnecessary_library_directive,unnecessary_library_name,unused_import,unused_local_variable,unused_shown_name
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'aopd://advanced-recipes',
  'aopd://arg-rewrite',
  'aopd://around-advice',
  'aopd://auto-analytics',
  'aopd://basic-annotations',
  'aopd://code-coverage',
  'aopd://exception-guard',
  'aopd://feature-flags',
  'aopd://framework-patch',
  'aopd://home',
  'aopd://json-model',
  'aopd://network-tracing',
  'aopd://performance-build',
  'aopd://performance-frame',
  'aopd://performance-image',
  'aopd://performance-monitoring',
  'aopd://wildcard-coverage',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'Instance, static, constructor, library, regex pointcuts, and PointCut data.'
  ///
  /// [name] : 'aopd://advanced-recipes'
  ///
  /// [routeName] : 'Advanced recipes'
  ///
  /// [description] : 'Instance, static, constructor, library, regex pointcuts, and PointCut data.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'core', 'order': '2', 'icon': 'tree', 'color': 'amber'}
  static const String aopdAdvancedRecipes = 'aopd://advanced-recipes';

  /// 'Advice rewrites a method’s inputs before it runs — PII redaction and input sanitizing.'
  ///
  /// [name] : 'aopd://arg-rewrite'
  ///
  /// [routeName] : 'Argument rewrite'
  ///
  /// [description] : 'Advice rewrites a method’s inputs before it runs — PII redaction and input sanitizing.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'behavior', 'order': '4', 'icon': 'rewrite', 'color': 'blue'}
  static const String aopdArgRewrite = 'aopd://arg-rewrite';

  /// 'Time a method (slow-call alert) and cache another by SKIPPING the original body.'
  ///
  /// [name] : 'aopd://around-advice'
  ///
  /// [routeName] : 'Around advice'
  ///
  /// [description] : 'Time a method (slow-call alert) and cache another by SKIPPING the original body.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'behavior', 'order': '1', 'icon': 'around', 'color': 'rose'}
  static const String aopdAroundAdvice = 'aopd://around-advice';

  /// 'A practical full-tracking demo inspired by real click analytics instrumentation.'
  ///
  /// [name] : 'aopd://auto-analytics'
  ///
  /// [routeName] : 'Auto analytics'
  ///
  /// [description] : 'A practical full-tracking demo inspired by real click analytics instrumentation.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'observability', 'order': '1', 'icon': 'click', 'color': 'blue'}
  static const String aopdAutoAnalytics = 'aopd://auto-analytics';

  /// 'Aspect, Execute, Call, FieldGet, Inject, and Add in small loops.'
  ///
  /// [name] : 'aopd://basic-annotations'
  ///
  /// [routeName] : 'Basic annotations'
  ///
  /// [description] : 'Aspect, Execute, Call, FieldGet, Inject, and Add in small loops.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'core', 'order': '1', 'icon': 'spark', 'color': 'teal'}
  static const String aopdBasicAnnotations = 'aopd://basic-annotations';

  /// 'Method-level coverage via woven hit-recording advice.'
  ///
  /// [name] : 'aopd://code-coverage'
  ///
  /// [routeName] : 'Code coverage'
  ///
  /// [description] : 'Method-level coverage via woven hit-recording advice.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'observability', 'order': '4', 'icon': 'coverage', 'color': 'green'}
  static const String aopdCodeCoverage = 'aopd://code-coverage';

  /// 'Woven try/catch turns a throwing method into a safe fallback — the app never crashes.'
  ///
  /// [name] : 'aopd://exception-guard'
  ///
  /// [routeName] : 'Exception guard'
  ///
  /// [description] : 'Woven try/catch turns a throwing method into a safe fallback — the app never crashes.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'behavior', 'order': '2', 'icon': 'guard', 'color': 'amber'}
  static const String aopdExceptionGuard = 'aopd://exception-guard';

  /// 'Route gray-release behavior through advice while business methods stay stable.'
  ///
  /// [name] : 'aopd://feature-flags'
  ///
  /// [routeName] : 'Feature flags'
  ///
  /// [description] : 'Route gray-release behavior through advice while business methods stay stable.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'behavior', 'order': '9', 'icon': 'flag', 'color': 'green'}
  static const String aopdFeatureFlags = 'aopd://feature-flags';

  /// 'Patch a private Flutter SDK method (text scaler) to clamp font scaling — no SDK fork.'
  ///
  /// [name] : 'aopd://framework-patch'
  ///
  /// [routeName] : 'Framework patch'
  ///
  /// [description] : 'Patch a private Flutter SDK method (text scaler) to clamp font scaling — no SDK fork.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'compiler', 'order': '1', 'icon': 'patch', 'color': 'blue'}
  static const String aopdFrameworkPatch = 'aopd://framework-patch';

  /// 'AOPD Example Home'
  ///
  /// [name] : 'aopd://home'
  ///
  /// [routeName] : 'AOPD Example Home'
  ///
  /// [exts] : {'group': 'catalog', 'order': '0'}
  static const String aopdHome = 'aopd://home';

  /// 'Auto-serialize models with AOP instead of dart:mirrors — toJson has no field code.'
  ///
  /// [name] : 'aopd://json-model'
  ///
  /// [routeName] : 'JSON model'
  ///
  /// [description] : 'Auto-serialize models with AOP instead of dart:mirrors — toJson has no field code.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'compiler', 'order': '2', 'icon': 'json', 'color': 'teal'}
  static const String aopdJsonModel = 'aopd://json-model';

  /// 'Trace API calls with ids, latency, and status without request-code logging.'
  ///
  /// [name] : 'aopd://network-tracing'
  ///
  /// [routeName] : 'Network tracing'
  ///
  /// [description] : 'Trace API calls with ids, latency, and status without request-code logging.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'observability', 'order': '5', 'icon': 'network', 'color': 'blue'}
  static const String aopdNetworkTracing = 'aopd://network-tracing';

  /// 'Measure slow widget rebuilds produced by performRebuild.'
  ///
  /// [name] : 'aopd://performance-build'
  ///
  /// [routeName] : 'Build tracking'
  ///
  /// [description] : 'Measure slow widget rebuilds produced by performRebuild.'
  ///
  /// [exts] : {'group': 'performance', 'order': '1', 'icon': 'build', 'color': 'rose'}
  static const String aopdPerformanceBuild = 'aopd://performance-build';

  /// 'Measure frame timing and build/layout/paint phase costs.'
  ///
  /// [name] : 'aopd://performance-frame'
  ///
  /// [routeName] : 'Frame phases'
  ///
  /// [description] : 'Measure frame timing and build/layout/paint phase costs.'
  ///
  /// [exts] : {'group': 'performance', 'order': '2', 'icon': 'timeline', 'color': 'amber'}
  static const String aopdPerformanceFrame = 'aopd://performance-frame';

  /// 'Measure image cache miss and decode behavior.'
  ///
  /// [name] : 'aopd://performance-image'
  ///
  /// [routeName] : 'Image loading'
  ///
  /// [description] : 'Measure image cache miss and decode behavior.'
  ///
  /// [exts] : {'group': 'performance', 'order': '3', 'icon': 'image', 'color': 'blue'}
  static const String aopdPerformanceImage = 'aopd://performance-image';

  /// 'A practical AOP demo for widget rebuilds, frame phases, and image loading.'
  ///
  /// [name] : 'aopd://performance-monitoring'
  ///
  /// [routeName] : 'Performance monitoring'
  ///
  /// [description] : 'A practical AOP demo for widget rebuilds, frame phases, and image loading.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'observability', 'order': '2', 'icon': 'speed', 'color': 'rose'}
  static const String aopdPerformanceMonitoring =
      'aopd://performance-monitoring';

  /// 'One regex pointcut instruments a whole package subtree — no per-class annotation.'
  ///
  /// [name] : 'aopd://wildcard-coverage'
  ///
  /// [routeName] : 'Wildcard coverage'
  ///
  /// [description] : 'One regex pointcut instruments a whole package subtree — no per-class annotation.'
  ///
  /// [exts] : {'group': 'demo', 'subgroup': 'observability', 'order': '5', 'icon': 'wildcard', 'color': 'teal'}
  static const String aopdWildcardCoverage = 'aopd://wildcard-coverage';
}
