// dart format off
// coverage:ignore-file
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unnecessary_library_directive,unnecessary_library_name,unused_import,unused_local_variable,unused_shown_name
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';

import 'app/example_home_page.dart';
import 'demos/advanced/advanced_recipes_page.dart';
import 'demos/analytics/auto_analytics_page.dart';
import 'demos/arg_rewrite/arg_rewrite_page.dart';
import 'demos/around_advice/around_advice_page.dart';
import 'demos/basic/basic_annotations_page.dart';
import 'demos/code_coverage/code_coverage_page.dart';
import 'demos/code_coverage/wildcard_coverage_page.dart';
import 'demos/exception_guard/exception_guard_page.dart';
import 'demos/feature_flag/feature_flag_page.dart';
import 'demos/framework_patch/framework_patch_page.dart';
import 'demos/json_model/json_model_page.dart';
import 'demos/network_tracing/network_tracing_page.dart';
import 'demos/performance/performance_monitoring_page.dart';

/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
  PageBuilder? notFoundPageBuilder,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'aopd://advanced-recipes':
      return FFRouteSettings(
        name: 'aopd://advanced-recipes',
        routeName: 'Advanced recipes',
        description:
            'Instance, static, constructor, library, regex pointcuts, and PointCut data.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'core',
          'order': '2',
          'icon': 'tree',
          'color': 'amber',
        },
        builder: () =>
            AdvancedRecipesPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://arg-rewrite':
      return FFRouteSettings(
        name: 'aopd://arg-rewrite',
        routeName: 'Argument rewrite',
        description:
            'Advice rewrites a method’s inputs before it runs — PII redaction and input sanitizing.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'behavior',
          'order': '4',
          'icon': 'rewrite',
          'color': 'blue',
        },
        builder: () => ArgRewritePage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://around-advice':
      return FFRouteSettings(
        name: 'aopd://around-advice',
        routeName: 'Around advice',
        description:
            'Time a method (slow-call alert) and cache another by SKIPPING the original body.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'behavior',
          'order': '1',
          'icon': 'around',
          'color': 'rose',
        },
        builder: () => AroundAdvicePage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://auto-analytics':
      return FFRouteSettings(
        name: 'aopd://auto-analytics',
        routeName: 'Auto analytics',
        description:
            'A practical full-tracking demo inspired by real click analytics instrumentation.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'observability',
          'order': '1',
          'icon': 'click',
          'color': 'blue',
        },
        builder: () => AutoAnalyticsPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://basic-annotations':
      return FFRouteSettings(
        name: 'aopd://basic-annotations',
        routeName: 'Basic annotations',
        description:
            'Aspect, Execute, Call, FieldGet, Inject, and Add in small loops.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'core',
          'order': '1',
          'icon': 'spark',
          'color': 'teal',
        },
        builder: () =>
            BasicAnnotationsPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://code-coverage':
      return FFRouteSettings(
        name: 'aopd://code-coverage',
        routeName: 'Code coverage',
        description: 'Method-level coverage via woven hit-recording advice.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'observability',
          'order': '4',
          'icon': 'coverage',
          'color': 'green',
        },
        builder: () => CodeCoveragePage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://exception-guard':
      return FFRouteSettings(
        name: 'aopd://exception-guard',
        routeName: 'Exception guard',
        description:
            'Woven try/catch turns a throwing method into a safe fallback — the app never crashes.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'behavior',
          'order': '2',
          'icon': 'guard',
          'color': 'amber',
        },
        builder: () => ExceptionGuardPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://feature-flags':
      return FFRouteSettings(
        name: 'aopd://feature-flags',
        routeName: 'Feature flags',
        description:
            'Route gray-release behavior through advice while business methods stay stable.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'behavior',
          'order': '9',
          'icon': 'flag',
          'color': 'green',
        },
        builder: () => FeatureFlagPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://framework-patch':
      return FFRouteSettings(
        name: 'aopd://framework-patch',
        routeName: 'Framework patch',
        description:
            'Patch a private Flutter SDK method (text scaler) to clamp font scaling — no SDK fork.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'compiler',
          'order': '1',
          'icon': 'patch',
          'color': 'blue',
        },
        builder: () => FrameworkPatchPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://home':
      return FFRouteSettings(
        name: 'aopd://home',
        routeName: 'AOPD Example Home',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'catalog', 'order': '0'},
        builder: () => ExampleHomePage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://json-model':
      return FFRouteSettings(
        name: 'aopd://json-model',
        routeName: 'JSON model',
        description:
            'Auto-serialize models with AOP instead of dart:mirrors — toJson has no field code.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'compiler',
          'order': '2',
          'icon': 'json',
          'color': 'teal',
        },
        builder: () => JsonModelPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://network-tracing':
      return FFRouteSettings(
        name: 'aopd://network-tracing',
        routeName: 'Network tracing',
        description:
            'Trace API calls with ids, latency, and status without request-code logging.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'observability',
          'order': '5',
          'icon': 'network',
          'color': 'blue',
        },
        builder: () => NetworkTracingPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://performance-build':
      return FFRouteSettings(
        name: 'aopd://performance-build',
        routeName: 'Build tracking',
        description: 'Measure slow widget rebuilds produced by performRebuild.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'performance',
          'order': '1',
          'icon': 'build',
          'color': 'rose',
        },
        builder: () =>
            PerformanceBuildPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://performance-frame':
      return FFRouteSettings(
        name: 'aopd://performance-frame',
        routeName: 'Frame phases',
        description: 'Measure frame timing and build/layout/paint phase costs.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'performance',
          'order': '2',
          'icon': 'timeline',
          'color': 'amber',
        },
        builder: () =>
            PerformanceFramePage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://performance-image':
      return FFRouteSettings(
        name: 'aopd://performance-image',
        routeName: 'Image loading',
        description: 'Measure image cache miss and decode behavior.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'performance',
          'order': '3',
          'icon': 'image',
          'color': 'blue',
        },
        builder: () =>
            PerformanceImagePage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://performance-monitoring':
      return FFRouteSettings(
        name: 'aopd://performance-monitoring',
        routeName: 'Performance monitoring',
        description:
            'A practical AOP demo for widget rebuilds, frame phases, and image loading.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'observability',
          'order': '2',
          'icon': 'speed',
          'color': 'rose',
        },
        builder: () =>
            PerformanceMonitoringPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'aopd://wildcard-coverage':
      return FFRouteSettings(
        name: 'aopd://wildcard-coverage',
        routeName: 'Wildcard coverage',
        description:
            'One regex pointcut instruments a whole package subtree — no per-class annotation.',
        arguments: arguments,
        exts: <String, dynamic>{
          'group': 'demo',
          'subgroup': 'observability',
          'order': '5',
          'icon': 'wildcard',
          'color': 'teal',
        },
        builder: () =>
            WildcardCoveragePage(key: asT<Key?>(safeArguments['key'])),
      );
    default:
      return FFRouteSettings(
        name: FFRoute.notFoundName,
        routeName: FFRoute.notFoundRouteName,
        builder: notFoundPageBuilder ?? () => Container(),
      );
  }
}
